name: CWE Filter CI

on:
  workflow_dispatch:
    inputs:
      languages:
        description: 'Comma-separated programming languages (e.g. Java,Python,C#)'
        required: true
        default: 'Java,Python'
      mode:
        description: 'Filter mode (or/and)'
        required: true
        default: 'or'

jobs:
  filter-cwe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run CWE Filter Script (custom params)
        run: |
          CMD="python filter_cwe.py --languages '${{ github.event.inputs.languages }}'"
          if [ -n "${{ github.event.inputs.mode }}" ]; then
            CMD="$CMD --mode ${{ github.event.inputs.mode }}"
          fi
          eval $CMD > filtered_cwe.txt

      - name: Upload filtered_cwe.txt as CI artifact
        uses: actions/upload-artifact@v3
        with:
          name: CWE-filter-result
          path: filtered_cwe.txt

      - name: (Optional) Run tests
        run: pytest tests/test.py
